package dev.adrian.showdown

import java.io.File
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class ShowdownMoveEffectsContractTest {
    @Test
    fun fullShowdownSceneKeepsWeatherAndTerrainLayersVisible() {
        val source = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()
        val hideChrome = source.substringAfter("function hideChrome()").substringBefore("function observeChrome()")
        val hiddenElements = hideChrome.substringBefore("].forEach(function (element)")

        assertFalse(hiddenElements.contains("scene.\${'$'}weather"))
        assertFalse(hiddenElements.contains("scene.\${'$'}terrain"))
        assertTrue(hideChrome.contains("scene.\${'$'}terrain, scene.\${'$'}weather"))
    }

    @Test
    fun incrementalBattleStartsPausedAndUsesTheNativePlaybackClock() {
        val source = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()

        assertTrue(source.contains("private val mainHandler = Handler(Looper.getMainLooper())"))
        assertTrue(source.contains("if (Looper.myLooper() != Looper.getMainLooper())"))
        assertTrue(source.contains("applyProtocol(lines, battleLogGeneration, effectsBarrierToken, identitiesByLine)"))
        assertTrue(source.contains("mainHandler.post { release() }"))
        assertTrue(source.contains("private fun cleanupOnMainThread()"))
        assertTrue(source.contains("mainHandler.post(cleanup)"))
        assertTrue(source.contains("new Battle({ id: 'showdownds', paused: true,"))
        assertTrue(source.contains("if (battle.paused) battle.play();"))
        assertTrue(source.contains("var nativeBattlePerspective = 'p1';"))
        assertTrue(source.contains("function applyNativeBattlePerspective()"))
        assertTrue(source.contains("parser.perspective = battle.mySide.sideid;"))
        assertTrue(source.contains("function isPerspectiveOrAlly(side, perspective)"))
        assertTrue(source.contains("var ally = {p1: 'p3', p2: 'p4', p3: 'p1', p4: 'p2'}[perspective];"))
        assertTrue(source.contains("parser.team = function (side, isFar)"))
        assertTrue(source.contains("parser.party = function (side)"))
        assertTrue(source.contains("setPerspective: function (side)"))
        assertTrue(source.contains("this.scene.__showdownNativeResultCues = [];"))
        assertTrue(source.contains("nativeMoveStarted();"))
        assertTrue(source.contains("function nativeAnnouncerCue(value)"))
        assertTrue(source.contains("function scheduleNativeAnnouncerCue(scene, value)"))
        assertTrue(source.contains("function clearNativeCueTimers(scene, clearAnnouncer)"))
        assertTrue(source.contains("if (clearAnnouncer !== false && scene.__showdownNativeAnnouncerTimers)"))
        assertTrue(source.contains("scene.__showdownNativeAnnouncerTimers.push(timer);"))
        assertTrue(source.contains("this.scene.__showdownNativeAnnouncerDamagePlayed = false;"))
        assertTrue(source.contains("this.scene.__showdownNativeAnnouncerMultiHit = !!(move && move.multihit);"))
        assertTrue(source.contains("scheduleNativeAnnouncerCue(this.scene, 'move');"))
        assertTrue(source.contains("scheduleNativeAnnouncerCue(this, announcerCue);"))
        assertTrue(source.contains("scheduleNativeAnnouncerCue(this.scene, 'multi_hit');"))
        assertTrue(source.contains("if (args[0] === '-status' && args[2] === 'par') announcerResultCue = 'paralysis';"))
        assertTrue(source.contains("if (args[0] === '-status' && args[2] === 'slp') announcerResultCue = 'sleep';"))
        assertTrue(source.contains("if (args[0] === '-status' && args[2] === 'frz') announcerResultCue = 'freeze';"))
        assertTrue(source.contains("if (args[0] === '-status' && args[2] === 'tox') announcerResultCue = 'toxic_poison';"))
        assertTrue(source.contains("if (args[0] === '-start' && args[2] === 'confusion') announcerResultCue = 'confusion';"))
        assertTrue(source.contains("if (args[0] === '-boost' && magnitude !== 0) announcerResultCue = magnitude > 0 ? 'stat_boost' : 'stat_drop';"))
        assertTrue(source.contains("if (args[0] === '-unboost' && magnitude !== 0) announcerResultCue = magnitude > 0 ? 'stat_drop' : 'stat_boost';"))
        assertTrue(source.contains("if (args[0] === '-setboost' && magnitude !== 0) announcerResultCue = magnitude > 0 ? 'stat_boost' : 'stat_drop';"))
        assertTrue(source.contains("if (args[0] === '-clearpositiveboost' || args[0] === '-clearboost' || args[0] === '-clearallboost') announcerResultCue = 'stat_drop';"))
        assertTrue(source.contains("if (args[0] === '-clearnegativeboost' || args[0] === '-restoreboost') announcerResultCue = 'stat_boost';"))
        assertTrue(source.contains("private val announcerCueListener: (BattleAnnouncerCue) -> Unit = {}"))
        assertTrue(source.contains("fun announcer(value: String)"))
        assertTrue(source.contains("function scheduleNativeCue(scene, value)"))
        assertTrue(source.contains("var delay = Math.max(0, Number(scene.timeOffset) || 0);"))
        assertTrue(source.contains("scene.__showdownNativeCueTimers.push(timer);"))
        assertTrue(source.contains("var originalStopAnimation = BattleScene.prototype.stopAnimation;"))
        assertTrue(source.contains("clearNativeCueTimers(this, !(this.battle && this.battle.paused));"))
        assertTrue(source.contains("clearNativeCueTimers(battle.scene);"))
        assertTrue(source.contains("var originalUseMove = Battle.prototype.useMove;"))
        assertTrue(source.contains("Battle.prototype.useMove = function (pokemon, move)"))
        assertTrue(source.contains("function moveCanDamage(move)"))
        assertTrue(source.contains("if (!move) return false;"))
        assertTrue(source.contains("var category = String(move.category || '').toLowerCase();"))
        assertTrue(source.contains("if (category !== 'status') return true;"))
        assertTrue(source.contains("typeof move.damage === 'function' || typeof move.damage === 'number' || move.damage === 'level' || typeof move.damageCallback === 'function'"))
        assertTrue(source.contains("return originalUseMove.apply(this, arguments);"))
        assertTrue(source.contains("nativeBattleStarted();"))
        assertTrue(source.contains("function installBattleLogHooks()"))
        assertTrue(source.contains("var originalAdd = BattleLog.prototype.add;"))
        assertTrue(source.contains("BattleLog.prototype.add = function (args, kwArgs)"))
        assertTrue(source.contains("nativeJoinLeaveMarkup(this);"))
        assertTrue(source.contains("function nativeUpdateJoinLeaveUser(instance, previous, next)"))
        assertTrue(source.contains("nativeUpdateJoinLeaveUser(this, args[2], args[1]);"))
        assertTrue(source.contains("' renamed from '"))
        assertTrue(source.contains("var nativeJoinLeaveKey = null;"))
        assertTrue(source.contains("var nativeRenameKey = null;"))
        assertTrue(source.contains("var captureNativeBattleLog = true;"))
        assertTrue(source.contains("if (!captureNativeBattleLog || !window.ShowdownNativeBattleLog || !value) return;"))
        assertTrue(source.contains("function nativeBattleLogSynchronized(generation)"))
        assertTrue(source.contains("captureNativeBattleLog = false;"))
        assertTrue(source.contains("captureNativeBattleLog = true;"))
        assertTrue(source.contains("BattleLog.prototype.addDiv = function (className, html)"))
        assertTrue(source.contains("BattleLog.prototype.addBattleMessage = function (args, kwArgs)"))
        assertTrue(source.contains("nativeBattleLog('Turn ' + args[1]);"))
        assertTrue(source.contains("var originalChangeUhtml = BattleLog.prototype.changeUhtml;"))
        assertTrue(source.contains("BattleLog.prototype.changeUhtml = function (id, htmlSrc, forceAdd)"))
        assertTrue(source.contains("var nativeBattleLogMarkupActive = false;"))
        assertTrue(source.contains("if (!nativeBattleLogMarkupActive) nativeBattleLog(html, className);"))
        assertTrue(source.contains("if (String(className || '').split(/\\s+/).indexOf('chat') >= 0) return;"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.markup(String(id || ''), String(value), nativeBattleLogGeneration);"))
        assertTrue(source.contains("nativeBattleMarkup(id, htmlSrc);"))
        assertFalse(source.contains("this.battleParser.parseArgs(args, kwArgs || {}).trim()"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.entry("))
        assertTrue(source.contains("JSON.stringify(nativeBattleLogIdentity)"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.synced(Number(generation) || 0);"))
        assertTrue(source.contains("nativeBattleLogSynchronized(generation);"))
        assertTrue(source.contains("receive: function (lines, generation, synchronizeBattleLog, protocolLineIdentities, effectsBarrierToken)"))
        assertTrue(source.contains("function add(lines, generation, synchronizeBattleLog, protocolLineIdentities, effectsBarrierToken)"))
        assertTrue(source.contains("add(lines, generation, synchronizeBattleLog, protocolLineIdentities, effectsBarrierToken);"))
        assertTrue(source.contains("ShowdownBattleLogFilter.visibleEntries(value)"))
        assertTrue(source.contains("const val NATIVE_BATTLE_LOG_BRIDGE = \"ShowdownNativeBattleLog\""))
        assertTrue(source.contains("new MutationObserver(function ()"))
        assertTrue(source.contains("chromeObserver.observe(document.getElementById('battle'), { childList: true, subtree: true });"))
        assertTrue(source.contains("function destroyBattle()"))
        assertTrue(source.contains("if (battle.scene) {"))
        assertTrue(source.contains("battle.scene.stopAnimation();"))
        assertTrue(source.contains(".result { display: none !important; }"))
        assertTrue(source.contains("release: function ()"))
        assertFalse(source.contains("requestAnimationFrame(keepChromeHidden)"))
        assertFalse(source.contains("var hideFrame = 0;"))
        assertTrue(source.contains("updateAcceleration.call(scene);"))
        assertTrue(source.contains("scene.acceleration = animationSpeed;"))
        assertTrue(source.contains("Math.max(\${BattlePlaybackSpeed.MINIMUM}, Math.min(\${BattlePlaybackSpeed.MAXIMUM}, Number(speed) || 1))"))
        assertFalse(source.contains("scene.acceleration *= animationSpeed;"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageArmed = moveCanDamage(move);"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageWindow = this.scene.__showdownNativeDamageArmed;"))
        assertTrue(source.contains("var originalRunMajor = Battle.prototype.runMajor;"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageWindow = false;"))
        assertTrue(source.contains("this.scene.__showdownNativeDamagePlayed = false;"))
        assertTrue(source.contains("this.scene.__showdownNativeHealthEvents = [];"))
        assertTrue(source.contains("var healthEventAllowed = !kwArgs.silent;"))
        assertTrue(source.contains("if (healthEventAllowed && args[0] === '-damage')"))
        assertTrue(source.contains("if (healthEventAllowed && args[0] === '-sethp')"))
        assertTrue(source.contains("function queueNativeHealthEvent(scene, target, kind)"))
        assertTrue(source.contains("function takeNativeHealthEvent(scene, pokemon)"))
        assertTrue(source.contains("var healthEvent = takeNativeHealthEvent(this, arguments[0]);"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageWindow = false;"))
        assertTrue(source.contains("var shouldCueDamage = healthEvent === 'damage' && this.animating"))
        assertTrue(source.contains("scheduleNativeCue(this, 'generic_damage');"))
        assertTrue(source.contains("if (resultCue && this.animating && !this.__showdownNativeAudioSilent)"))
        assertTrue(source.contains("var originalHealAnim = BattleScene.prototype.healAnim;"))
        assertFalse(source.contains("args[0] === '-item' || args[0] === '-eat'"))
        assertTrue(source.contains("function setHpValue(pokemon, health)"))
        assertTrue(source.contains("function isDirectMoveDamage(source)"))
        assertTrue(source.contains("return !normalized || /^move\\s*:/i.test(normalized);"))
        assertFalse(source.contains("return !normalized;"))
        assertTrue(source.contains("function keepsDirectMoveDamageWindow(args)"))
        assertTrue(source.contains("args[0] === '-anim' || args[0] === '-crit'"))
        assertTrue(source.contains("args[0] !== '-damage' && args[0] !== '-sethp' && !keepsDirectMoveDamageWindow(args)"))
        assertTrue(source.contains("var directMoveDamage = this.scene.__showdownNativeDamageWindow && isDirectMoveDamage(kwArgs.from);"))
        assertTrue(source.contains("queueNativeHealthEvent(this.scene, args[1], directMoveDamage ? 'damage' : 'other');"))
        assertTrue(source.contains("queueNativeHealthEvent(this.scene, args[1], 'heal');"))
        assertTrue(source.contains("var setHpTarget = this.getPokemon(args[setHpIndex]);"))
        assertTrue(source.contains("var nextHp = setHpValue(setHpTarget, args[setHpIndex + 1]);"))
        assertTrue(source.contains("if (directMoveDamage) {"))
        assertTrue(source.contains("if (setHpTarget && nextHp !== null) queueNativeHealthEvent(this.scene, args[setHpIndex], nextHp < setHpTarget.hp ? 'damage' : nextHp > setHpTarget.hp ? 'heal' : 'other');"))
        assertTrue(source.contains("var previousAudioSilent = !!this.scene.__showdownNativeAudioSilent;"))
        assertTrue(source.contains("this.scene.__showdownNativeAudioSilent = previousAudioSilent;"))
        assertFalse(source.contains("this.scene.__showdownNativeHealthEvents = [];\n                                this.scene.__showdownNativeAudioSilent = false;"))
        assertFalse(source.contains("setHpTarget.healthParse(args[setHpIndex + 1])"))
        assertTrue(source.contains("args[0] === '-clearpositiveboost'"))
        assertTrue(source.contains("args[0] === '-clearnegativeboost'"))
        assertTrue(source.contains("fun battleStarted()"))
        assertTrue(source.contains("resetAudio()"))
        assertTrue(source.contains("fun moveStarted()"))
        assertTrue(source.contains("resetMoveAudio()"))
        assertTrue(source.contains("if (!this.scene.__showdownNativeResultCues) this.scene.__showdownNativeResultCues = [];"))
        assertTrue(source.contains("this.__showdownNativeResultCues && this.__showdownNativeResultCues.length"))
        assertTrue(source.contains("var resultCue = this.__showdownNativeResultCues && this.__showdownNativeResultCues.length ? this.__showdownNativeResultCues.shift() : null;"))
        assertTrue(source.contains("this.scene.__showdownNativeResultCues.push(resultCue);"))
        assertTrue(source.contains("scheduleNativeCue(this, resultCue);"))
        assertFalse(source.contains("__showdownNativeResultCue = null"))
        assertTrue(source.contains("this.scene.__showdownNativeAudioSilent = !!kwArgs.silent;"))
        assertFalse(source.contains("protocolHistoryProvider"))
        assertTrue(source.contains("flushPendingPackets(allowSeedWhilePaused = true)"))
        assertTrue(source.contains("private val nativeIdlePauseRunnable = Runnable"))
        assertTrue(source.contains("NATIVE_IDLE_CHECK_DELAY_MILLIS"))
        assertTrue(source.contains("window.ShowdownNativeEffects.pauseWhenIdle();"))
        assertTrue(source.contains("var nativeIdlePauseTimer = null;"))
        assertTrue(source.contains("function requestNativeIdlePause()"))
        assertTrue(source.contains("if (battle.atQueueEnd)"))
        assertTrue(source.contains("pauseWhenIdle: function ()"))
        assertTrue(source.contains("clearNativeIdlePauseTimer();"))
        assertFalse(source.contains("if (resultCue && this.scene.__showdownNativeResultCue === resultCue)"))
        assertFalse(source.contains("BattlePlaybackTiming.pauseAfter(packet)"))
        assertFalse(source.contains("postDelayed(flushRunnable"))
        assertFalse(source.contains("var originalRunMoveAnim = BattleScene.prototype.runMoveAnim;"))
    }

    @Test
    fun webViewLoadPreservesQueuedProtocolPacketsAndBarrierTokens() {
        val source = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()
        val pageFinishedStart = source.indexOf("override fun onPageFinished")
        val pageFinishedEnd = source.indexOf("loadDataWithBaseURL", pageFinishedStart)
        val pageFinished = source.substring(pageFinishedStart, pageFinishedEnd)

        assertTrue(pageFinishedStart >= 0)
        assertTrue(pageFinishedEnd > pageFinishedStart)
        assertFalse(pageFinished.contains("seed("))
        assertTrue(pageFinished.contains("initializeJavascriptIfReady()"))
        assertTrue(source.contains("private var javascriptReady = false"))
        assertTrue(source.contains("fun ready()"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.ready();"))
        assertTrue(source.contains("if ((!allowSeedWhilePaused && playbackPaused) || !javascriptReady) return"))
        assertTrue(source.contains("effectsBarrierToken: Long = 0L"))
        assertTrue(source.contains("pendingPackets.add("))
    }

    @Test
    fun rendererRecoveryReseedsHistorySilentlyAndKeepsItsBarrierToken() {
        val source = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()

        assertTrue(source.contains("fun recoverFromProtocolHistory(lines: List<String>, effectsBarrierToken: Long)"))
        assertTrue(source.contains("pendingPackets.resetWith(packet, effectsBarrierToken)"))
        assertTrue(source.contains("seed: function (lines, effectsBarrierToken)"))
        assertTrue(source.contains("add(lines, 0, false, [], barrierToken);"))
        assertTrue(source.contains("nativeSeedAnimationOff"))
        assertTrue(source.contains("nativeBattleRecovered()"))
        assertTrue(source.contains("nativeBattleEffectsReachedQueueEnd();"))
        assertTrue(source.contains("fun battleRecovered()"))
    }

    @Test
    fun nativeBattleLogUsesTheGenerationOfItsQueuedShowdownStep() {
        val source = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()
        val runHookStart = source.indexOf("Battle.prototype.run = function")
        assertTrue(runHookStart >= 0)
        val runHookEnd = source.indexOf("};", runHookStart)
        val runHook = source.substring(runHookStart, runHookEnd)
        assertTrue(runHook.contains("nativeBattleLogGenerationByStep[stepIndex]"))
        assertTrue(runHook.contains("if (generation === null)"))
        assertTrue(source.contains("var nativeBattleLogGenerationByStep = [];"))
        assertTrue(source.contains("nativeBattleLogGenerationByStep = [];"))
        assertTrue(source.contains("nativeBattleLogGenerationByStep[stepIndex] = generation === undefined ? null : Number(generation) || 0;"))
        assertTrue(source.contains("var stepIndex = battle.stepQueue.length;"))
        assertTrue(source.contains("function add(lines, generation, synchronizeBattleLog, protocolLineIdentities, effectsBarrierToken)"))
        assertTrue(source.contains("add(lines, generation, synchronizeBattleLog, protocolLineIdentities, effectsBarrierToken);"))
        assertFalse(source.contains("nativeBattleLogGeneration = Number(generation) || 0;"))
    }

    @Test
    fun nativeBattleLogSyncWaitsUntilItsLastQueuedStepIsParsed() {
        val source = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()
        val runHookStart = source.indexOf("Battle.prototype.run = function")
        val receiveStart = source.indexOf("receive: function (lines, generation, synchronizeBattleLog, protocolLineIdentities, effectsBarrierToken)")
        val receiveEnd = source.indexOf("setSpeed: function (speed)", receiveStart)
        val runHook = source.substring(runHookStart, source.indexOf("};", runHookStart))
        val receive = source.substring(receiveStart, receiveEnd)

        assertTrue(source.contains("var nativeBattleLogSyncGenerationByStep = [];"))
        assertTrue(runHook.contains("nativeBattleLogSyncGenerationByStep[stepIndex]"))
        assertTrue(runHook.contains("if (!preempt && this.currentStep === stepIndex)"))
        assertTrue(runHook.contains("nativeBattleLogSynchronized(synchronizedGeneration);"))
        assertTrue(source.contains("nativeBattleLogSyncGenerationByStep[finalStepIndex] = Number(generation) || 0;"))
        assertFalse(receive.contains("nativeBattleLogSynchronized(generation);"))
    }

    @Test
    fun nativeBattleLogCarriesTheProtocolLineIdentityThatProducedIt() {
        val effectsSource = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()
        val sessionSource = File("src/main/kotlin/dev/adrian/showdown/BattleSession.kt").readText()
        val runHookStart = effectsSource.indexOf("Battle.prototype.run = function")
        val runHook = effectsSource.substring(runHookStart, effectsSource.indexOf("};", runHookStart))

        assertTrue(runHook.contains("nativeBattleLogIdentitiesByStep[stepIndex]"))
        assertTrue(runHook.contains("nativeBattleLogIdentity = previousIdentity;"))
        assertTrue(effectsSource.contains("JSON.stringify(nativeBattleLogIdentity)"))
        assertTrue(effectsSource.contains("protocolLineIdentities[index] || []"))
        assertTrue(effectsSource.contains("identitiesByLine: List<BattleSession.ProtocolLineIdentity>"))
        assertTrue(sessionSource.contains("activeProtocolMessageIdsByLine.getOrNull(activeProtocolLineIndex)?.add(messageId)"))
        assertTrue(sessionSource.contains("protocolMessageIds: List<Long> = emptyList()"))
        assertTrue(sessionSource.contains("protocolEventId?.let(protocolLineSceneContextsByEventId::get)"))
    }

    @Test
    fun nativeEffectsBarrierWaitsForShowdownQueueEnd() {
        val source = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()
        val creation = source.substringAfter("function createBattle()").substringBefore("function add(lines")
        val receive = source.substringAfter("function add(lines, generation, synchronizeBattleLog, effectsBarrierToken)")
            .substringBefore("window.addEventListener('resize', layout)")

        assertTrue(creation.contains("battle.subscription = function (state)"))
        assertTrue(creation.contains("state === 'atqueueend'"))
        assertTrue(receive.contains("nativeEffectsBarrierTokenByStep[finalStepIndex] = Number(effectsBarrierToken);"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.effectsIdle(normalizedToken);"))
        assertTrue(source.contains("fun effectsIdle(token: Long)"))
        assertFalse(source.substringAfter("Battle.prototype.run = function").substringBefore("var originalAdd = BattleLog.prototype.add")
            .contains("nativeBattleEffectsIdle("))
    }

    @Test
    fun pausedReplayAppliesItsInitialChunkBeforePausingPlayback() {
        val source = File("src/main/kotlin/dev/adrian/showdown/MainActivity.kt").readText()
        val enqueueIndex = source.indexOf("enqueueBattlePlayback(null, null, replayLines, resetOnBattleInit = false)")
        val pauseIndex = source.indexOf("if (replayStartsPaused) setReplayPaused(true)", enqueueIndex)

        assertTrue(enqueueIndex >= 0)
        assertTrue(pauseIndex > enqueueIndex)
    }

    @Test
    fun releasesNativeWebViewWithABoundedFallback() {
        val source = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()

        assertTrue(source.contains("private var cleanupCompleted = false"))
        assertTrue(source.contains("private val releaseFallbackRunnable = Runnable { cleanupOnMainThread() }"))
        assertTrue(source.contains("mainHandler.postDelayed(releaseFallbackRunnable, RELEASE_FALLBACK_DELAY_MILLIS)"))
        assertTrue(source.contains("if (cleanupCompleted) return"))
        assertTrue(source.contains("const val RELEASE_FALLBACK_DELAY_MILLIS = 250L"))
    }
}
