package dev.adrian.showdown

import java.io.File
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class ShowdownMoveEffectsContractTest {
    @Test
    fun incrementalBattleStartsPausedAndUsesTheNativePlaybackClock() {
        val source = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()

        assertTrue(source.contains("new Battle({ id: 'showdownds', paused: true,"))
        assertTrue(source.contains("if (battle.paused) battle.play();"))
        assertTrue(source.contains("var nativeBattlePerspective = 'p1';"))
        assertTrue(source.contains("function applyNativeBattlePerspective()"))
        assertTrue(source.contains("battle.scene.log.battleParser.perspective = battle.mySide.sideid;"))
        assertTrue(source.contains("setPerspective: function (side)"))
        assertTrue(source.contains("this.scene.__showdownNativeResultCues = [];"))
        assertTrue(source.contains("nativeMoveStarted();"))
        assertTrue(source.contains("function clearNativeCueTimers(scene)"))
        assertTrue(source.contains("function scheduleNativeCue(scene, value)"))
        assertTrue(source.contains("var delay = Math.max(0, Number(scene.timeOffset) || 0);"))
        assertTrue(source.contains("scene.__showdownNativeCueTimers.push(timer);"))
        assertTrue(source.contains("var originalStopAnimation = BattleScene.prototype.stopAnimation;"))
        assertTrue(source.contains("clearNativeCueTimers(this);"))
        assertTrue(source.contains("var originalUseMove = Battle.prototype.useMove;"))
        assertTrue(source.contains("Battle.prototype.useMove = function (pokemon, move)"))
        assertTrue(source.contains("function moveCanDamage(move)"))
        assertTrue(source.contains("var category = String(move.category || '').toLowerCase();"))
        assertTrue(source.contains("if (category === 'status') return false;"))
        assertTrue(source.contains("if (category === 'physical' || category === 'special') return true;"))
        assertTrue(source.contains("var hasFixedDamage = move.damage !== undefined && move.damage !== null && move.damage !== 0 && move.damage !== false;"))
        assertTrue(source.contains("var hasDamageCallback = typeof move.damageCallback === 'function' || move.basePowerCallback === true;"))
        assertTrue(source.contains("var dexMove = window.BattleMovedex && window.BattleMovedex[move.id];"))
        assertTrue(source.contains("var dexCategory = String(dexMove.category || '').toLowerCase();"))
        assertTrue(source.contains("hasDamageCallback = hasDamageCallback || typeof dexMove.damageCallback === 'function' || dexMove.basePowerCallback === true;"))
        assertTrue(source.contains("return originalUseMove.apply(this, arguments);"))
        assertTrue(source.contains("nativeBattleStarted();"))
        assertTrue(source.contains("function installBattleLogHooks()"))
        assertTrue(source.contains("var captureNativeBattleLog = true;"))
        assertTrue(source.contains("if (!captureNativeBattleLog || !window.ShowdownNativeBattleLog || !value) return;"))
        assertTrue(source.contains("function nativeBattleLogSynchronized(generation)"))
        assertTrue(source.contains("captureNativeBattleLog = false;"))
        assertTrue(source.contains("captureNativeBattleLog = true;"))
        assertTrue(source.contains("BattleLog.prototype.addDiv = function (className, html)"))
        assertTrue(source.contains("BattleLog.prototype.addBattleMessage = function (args, kwArgs)"))
        assertTrue(source.contains("nativeBattleLog('Turn ' + args[1]);"))
        assertTrue(source.contains("var originalChangeUhtml = BattleLog.prototype.changeUhtml;"))
        assertTrue(source.contains("BattleLog.prototype.changeUhtml = function (id, htmlSrc, forceAdd)"))
        assertTrue(source.contains("var nativeBattleLogMarkupActive = false;"))
        assertTrue(source.contains("if (!nativeBattleLogMarkupActive) nativeBattleLog(html);"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.markup(String(id || ''), String(value), nativeBattleLogGeneration);"))
        assertTrue(source.contains("nativeBattleMarkup(id, htmlSrc);"))
        assertFalse(source.contains("this.battleParser.parseArgs(args, kwArgs || {}).trim()"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.entry(String(value), nativeBattleLogGeneration);"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.synced(Number(generation) || 0);"))
        assertTrue(source.contains("nativeBattleLogSynchronized(generation);"))
        assertTrue(source.contains("receive: function (lines, generation, synchronizeBattleLog)"))
        assertTrue(source.contains("if (synchronizeBattleLog) nativeBattleLogSynchronized(generation);"))
        assertTrue(source.contains("ShowdownBattleLogFilter.visibleEntries(value)"))
        assertTrue(source.contains("const val NATIVE_BATTLE_LOG_BRIDGE = \"ShowdownNativeBattleLog\""))
        assertTrue(source.contains("new MutationObserver(function ()"))
        assertTrue(source.contains("chromeObserver.observe(document.getElementById('battle'), { childList: true, subtree: true });"))
        assertTrue(source.contains(".result { display: none !important; }"))
        assertTrue(source.contains("release: function ()"))
        assertFalse(source.contains("requestAnimationFrame(keepChromeHidden)"))
        assertFalse(source.contains("var hideFrame = 0;"))
        assertTrue(source.contains("updateAcceleration.call(scene);"))
        assertTrue(source.contains("scene.acceleration = animationSpeed;"))
        assertFalse(source.contains("scene.acceleration *= animationSpeed;"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageArmed = moveCanDamage(move);"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageWindow = this.scene.__showdownNativeDamageArmed;"))
        assertTrue(source.contains("var originalRunMajor = Battle.prototype.runMajor;"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageWindow = false;"))
        assertTrue(source.contains("this.scene.__showdownNativeDamagePlayed = false;"))
        assertTrue(source.contains("this.scene.__showdownNativeHealthEvents = [];"))
        assertTrue(source.contains("var healthEvent = this.__showdownNativeHealthEvents && this.__showdownNativeHealthEvents.length ? this.__showdownNativeHealthEvents.shift() : null;"))
        assertTrue(source.contains("var shouldCueDamage = healthEvent === 'damage' && this.animating"))
        assertTrue(source.contains("scheduleNativeCue(this, 'generic_damage');"))
        assertTrue(source.contains("var originalHealAnim = BattleScene.prototype.healAnim;"))
        assertTrue(source.contains("function setHpValue(pokemon, health)"))
        assertTrue(source.contains("function isDirectMoveDamage(source)"))
        assertTrue(source.contains("function keepsDirectMoveDamageWindow(args)"))
        assertTrue(source.contains("args[0] !== '-damage' && args[0] !== '-sethp' && !keepsDirectMoveDamageWindow(args)"))
        assertTrue(source.contains("var directMoveDamage = this.scene.__showdownNativeDamageWindow && isDirectMoveDamage(kwArgs.from);"))
        assertTrue(source.contains("this.scene.__showdownNativeHealthEvents.push(directMoveDamage ? 'damage' : 'other');"))
        assertTrue(source.contains("if (!directMoveDamage) this.scene.__showdownNativeDamageWindow = false;"))
        assertTrue(source.contains("this.scene.__showdownNativeHealthEvents.push('heal');"))
        assertTrue(source.contains("var setHpTarget = this.getPokemon(args[setHpIndex]);"))
        assertTrue(source.contains("var nextHp = setHpValue(setHpTarget, args[setHpIndex + 1]);"))
        assertTrue(source.contains("if (directMoveDamage) {"))
        assertTrue(source.contains("if (setHpTarget && nextHp !== null) this.scene.__showdownNativeHealthEvents.push(nextHp < setHpTarget.hp ? 'damage' : nextHp > setHpTarget.hp ? 'heal' : 'other');"))
        assertTrue(source.contains("var previousAudioSilent = !!this.scene.__showdownNativeAudioSilent;"))
        assertTrue(source.contains("this.scene.__showdownNativeAudioSilent = previousAudioSilent;"))
        assertFalse(source.contains("this.scene.__showdownNativeHealthEvents = [];\n                                this.scene.__showdownNativeAudioSilent = false;"))
        assertFalse(source.contains("setHpTarget.healthParse(args[setHpIndex + 1])"))
        assertTrue(source.contains("args[0] === '-clearpositiveboost'"))
        assertTrue(source.contains("args[0] === '-clearnegativeboost'"))
        assertTrue(source.contains("fun battleStarted()"))
        assertTrue(source.contains("resetAudio()"))
        assertTrue(source.contains("fun moveStarted()"))
        assertTrue(source.contains("resetMoveAudio()"))
        assertTrue(source.contains("if (!this.scene.__showdownNativeResultCues) this.scene.__showdownNativeResultCues = [];"))
        assertTrue(source.contains("this.__showdownNativeResultCues && this.__showdownNativeResultCues.length"))
        assertTrue(source.contains("shouldCueResult ? this.__showdownNativeResultCues.shift() : null;"))
        assertTrue(source.contains("this.scene.__showdownNativeResultCues.push(resultCue);"))
        assertTrue(source.contains("scheduleNativeCue(this, resultCue);"))
        assertFalse(source.contains("__showdownNativeResultCue = null"))
        assertTrue(source.contains("this.scene.__showdownNativeAudioSilent = !!kwArgs.silent;"))
        assertTrue(source.contains("seed(protocolHistoryProvider())"))
        assertTrue(source.contains("flushPendingPackets(allowSeedWhilePaused = true)"))
        assertFalse(source.contains("if (resultCue && this.scene.__showdownNativeResultCue === resultCue)"))
        assertFalse(source.contains("BattlePlaybackTiming.pauseAfter(packet)"))
        assertFalse(source.contains("postDelayed(flushRunnable"))
        assertFalse(source.contains("var originalRunMoveAnim = BattleScene.prototype.runMoveAnim;"))
    }

    @Test
    fun pausedReplayAppliesItsInitialChunkBeforePausingPlayback() {
        val source = File("src/main/kotlin/dev/adrian/showdown/MainActivity.kt").readText()
        val enqueueIndex = source.indexOf("enqueueBattlePlayback(null, null, replay.log.lines(), resetOnBattleInit = false)")
        val pauseIndex = source.indexOf("if (replayStartsPaused) setReplayPaused(true)", enqueueIndex)

        assertTrue(enqueueIndex >= 0)
        assertTrue(pauseIndex > enqueueIndex)
    }
}
