package dev.adrian.showdown

import java.io.File
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class ShowdownMoveEffectsContractTest {
    @Test
    fun incrementalBattleStartsPausedAndUsesTheNativePlaybackClock() {
        val source = File("src/main/kotlin/dev/adrian/showdown/ShowdownMoveEffectsView.kt").readText()

        assertTrue(source.contains("private val mainHandler = Handler(Looper.getMainLooper())"))
        assertTrue(source.contains("if (Looper.myLooper() != Looper.getMainLooper())"))
        assertTrue(source.contains("mainHandler.post { applyProtocol(lines, battleLogGeneration) }"))
        assertTrue(source.contains("mainHandler.post { release() }"))
        assertTrue(source.contains("private fun cleanupOnMainThread()"))
        assertTrue(source.contains("mainHandler.post(cleanup)"))
        assertTrue(source.contains("new Battle({ id: 'showdownds', paused: true,"))
        assertTrue(source.contains("if (battle.paused) battle.play();"))
        assertTrue(source.contains("var nativeBattlePerspective = 'p1';"))
        assertTrue(source.contains("function applyNativeBattlePerspective()"))
        assertTrue(source.contains("battle.scene.log.battleParser.perspective = battle.mySide.sideid;"))
        assertTrue(source.contains("setPerspective: function (side)"))
        assertTrue(source.contains("this.scene.__showdownNativeResultCues = [];"))
        assertTrue(source.contains("nativeMoveStarted();"))
        assertTrue(source.contains("function nativeAnnouncerCue(value)"))
        assertTrue(source.contains("function scheduleNativeAnnouncerCue(scene, value)"))
        assertTrue(source.contains("function clearNativeCueTimers(scene, clearAnnouncer)"))
        assertTrue(source.contains("if (clearAnnouncer !== false && scene.__showdownNativeAnnouncerTimers)"))
        assertTrue(source.contains("scene.__showdownNativeAnnouncerTimers.push(timer);"))
        assertTrue(source.contains("this.scene.__showdownNativeAnnouncerDamagePlayed = false;"))
        assertTrue(source.contains("this.scene.__showdownNativeAnnouncerMultiHit = !!(move && move.multihit);"))
        assertTrue(source.contains("scheduleNativeAnnouncerCue(this.scene, 'move');"))
        assertTrue(source.contains("scheduleNativeAnnouncerCue(this, announcerCue);"))
        assertTrue(source.contains("scheduleNativeAnnouncerCue(this.scene, 'multi_hit');"))
        assertTrue(source.contains("private val announcerCueListener: (BattleAnnouncerCue) -> Unit = {}"))
        assertTrue(source.contains("fun announcer(value: String)"))
        assertTrue(source.contains("function scheduleNativeCue(scene, value)"))
        assertTrue(source.contains("var delay = Math.max(0, Number(scene.timeOffset) || 0);"))
        assertTrue(source.contains("scene.__showdownNativeCueTimers.push(timer);"))
        assertTrue(source.contains("var originalStopAnimation = BattleScene.prototype.stopAnimation;"))
        assertTrue(source.contains("clearNativeCueTimers(this, !(this.battle && this.battle.paused));"))
        assertTrue(source.contains("clearNativeCueTimers(battle.scene);"))
        assertTrue(source.contains("var originalUseMove = Battle.prototype.useMove;"))
        assertTrue(source.contains("Battle.prototype.useMove = function (pokemon, move)"))
        assertTrue(source.contains("function moveCanDamage(move)"))
        assertTrue(source.contains("return !!move;"))
        assertFalse(source.contains("if (category === 'status') return false;"))
        assertFalse(source.contains("return category === 'physical' || category === 'special';"))
        assertTrue(source.contains("return originalUseMove.apply(this, arguments);"))
        assertTrue(source.contains("nativeBattleStarted();"))
        assertTrue(source.contains("function installBattleLogHooks()"))
        assertTrue(source.contains("var originalAdd = BattleLog.prototype.add;"))
        assertTrue(source.contains("BattleLog.prototype.add = function (args, kwArgs)"))
        assertTrue(source.contains("nativeJoinLeaveMarkup(this);"))
        assertTrue(source.contains("' renamed from '"))
        assertTrue(source.contains("var nativeJoinLeaveKey = null;"))
        assertTrue(source.contains("var nativeRenameKey = null;"))
        assertTrue(source.contains("var captureNativeBattleLog = true;"))
        assertTrue(source.contains("if (!captureNativeBattleLog || !window.ShowdownNativeBattleLog || !value) return;"))
        assertTrue(source.contains("function nativeBattleLogSynchronized(generation)"))
        assertTrue(source.contains("captureNativeBattleLog = false;"))
        assertTrue(source.contains("captureNativeBattleLog = true;"))
        assertTrue(source.contains("BattleLog.prototype.addDiv = function (className, html)"))
        assertTrue(source.contains("BattleLog.prototype.addBattleMessage = function (args, kwArgs)"))
        assertTrue(source.contains("nativeBattleLog('Turn ' + args[1]);"))
        assertTrue(source.contains("var originalChangeUhtml = BattleLog.prototype.changeUhtml;"))
        assertTrue(source.contains("BattleLog.prototype.changeUhtml = function (id, htmlSrc, forceAdd)"))
        assertTrue(source.contains("var nativeBattleLogMarkupActive = false;"))
        assertTrue(source.contains("if (!nativeBattleLogMarkupActive) nativeBattleLog(html);"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.markup(String(id || ''), String(value), nativeBattleLogGeneration);"))
        assertTrue(source.contains("nativeBattleMarkup(id, htmlSrc);"))
        assertFalse(source.contains("this.battleParser.parseArgs(args, kwArgs || {}).trim()"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.entry(String(value), nativeBattleLogGeneration);"))
        assertTrue(source.contains("window.ShowdownNativeBattleLog.synced(Number(generation) || 0);"))
        assertTrue(source.contains("nativeBattleLogSynchronized(generation);"))
        assertTrue(source.contains("receive: function (lines, generation, synchronizeBattleLog)"))
        assertTrue(source.contains("if (synchronizeBattleLog) nativeBattleLogSynchronized(generation);"))
        assertTrue(source.contains("ShowdownBattleLogFilter.visibleEntries(value)"))
        assertTrue(source.contains("const val NATIVE_BATTLE_LOG_BRIDGE = \"ShowdownNativeBattleLog\""))
        assertTrue(source.contains("new MutationObserver(function ()"))
        assertTrue(source.contains("chromeObserver.observe(document.getElementById('battle'), { childList: true, subtree: true });"))
        assertTrue(source.contains("function destroyBattle()"))
        assertTrue(source.contains("if (battle.scene) {"))
        assertTrue(source.contains("battle.scene.stopAnimation();"))
        assertTrue(source.contains(".result { display: none !important; }"))
        assertTrue(source.contains("release: function ()"))
        assertFalse(source.contains("requestAnimationFrame(keepChromeHidden)"))
        assertFalse(source.contains("var hideFrame = 0;"))
        assertTrue(source.contains("updateAcceleration.call(scene);"))
        assertTrue(source.contains("scene.acceleration = animationSpeed;"))
        assertTrue(source.contains("Math.max(\${BattlePlaybackSpeed.MINIMUM}, Math.min(\${BattlePlaybackSpeed.MAXIMUM}, Number(speed) || 1))"))
        assertFalse(source.contains("scene.acceleration *= animationSpeed;"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageArmed = moveCanDamage(move);"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageWindow = this.scene.__showdownNativeDamageArmed;"))
        assertTrue(source.contains("var originalRunMajor = Battle.prototype.runMajor;"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageWindow = false;"))
        assertTrue(source.contains("this.scene.__showdownNativeDamagePlayed = false;"))
        assertTrue(source.contains("this.scene.__showdownNativeHealthEvents = [];"))
        assertTrue(source.contains("var healthEventAllowed = !kwArgs.silent;"))
        assertTrue(source.contains("if (healthEventAllowed && args[0] === '-damage')"))
        assertTrue(source.contains("if (healthEventAllowed && args[0] === '-sethp')"))
        assertTrue(source.contains("function queueNativeHealthEvent(scene, target, kind)"))
        assertTrue(source.contains("function takeNativeHealthEvent(scene, pokemon)"))
        assertTrue(source.contains("var healthEvent = takeNativeHealthEvent(this, arguments[0]);"))
        assertTrue(source.contains("this.scene.__showdownNativeDamageWindow = false;"))
        assertTrue(source.contains("var shouldCueDamage = healthEvent === 'damage' && this.animating"))
        assertTrue(source.contains("scheduleNativeCue(this, 'generic_damage');"))
        assertTrue(source.contains("if (resultCue && this.animating && !this.__showdownNativeAudioSilent)"))
        assertTrue(source.contains("var originalHealAnim = BattleScene.prototype.healAnim;"))
        assertTrue(source.contains("function setHpValue(pokemon, health)"))
        assertTrue(source.contains("function isDirectMoveDamage(source)"))
        assertTrue(source.contains("return !normalized || /^move\\s*:/i.test(normalized);"))
        assertFalse(source.contains("return !normalized;"))
        assertTrue(source.contains("function keepsDirectMoveDamageWindow(args)"))
        assertTrue(source.contains("args[0] === '-anim' || args[0] === '-crit'"))
        assertTrue(source.contains("args[0] !== '-damage' && args[0] !== '-sethp' && !keepsDirectMoveDamageWindow(args)"))
        assertTrue(source.contains("var directMoveDamage = this.scene.__showdownNativeDamageWindow && isDirectMoveDamage(kwArgs.from);"))
        assertTrue(source.contains("queueNativeHealthEvent(this.scene, args[1], directMoveDamage ? 'damage' : 'other');"))
        assertTrue(source.contains("queueNativeHealthEvent(this.scene, args[1], 'heal');"))
        assertTrue(source.contains("var setHpTarget = this.getPokemon(args[setHpIndex]);"))
        assertTrue(source.contains("var nextHp = setHpValue(setHpTarget, args[setHpIndex + 1]);"))
        assertTrue(source.contains("if (directMoveDamage) {"))
        assertTrue(source.contains("if (setHpTarget && nextHp !== null) queueNativeHealthEvent(this.scene, args[setHpIndex], nextHp < setHpTarget.hp ? 'damage' : nextHp > setHpTarget.hp ? 'heal' : 'other');"))
        assertTrue(source.contains("var previousAudioSilent = !!this.scene.__showdownNativeAudioSilent;"))
        assertTrue(source.contains("this.scene.__showdownNativeAudioSilent = previousAudioSilent;"))
        assertFalse(source.contains("this.scene.__showdownNativeHealthEvents = [];\n                                this.scene.__showdownNativeAudioSilent = false;"))
        assertFalse(source.contains("setHpTarget.healthParse(args[setHpIndex + 1])"))
        assertTrue(source.contains("args[0] === '-clearpositiveboost'"))
        assertTrue(source.contains("args[0] === '-clearnegativeboost'"))
        assertTrue(source.contains("fun battleStarted()"))
        assertTrue(source.contains("resetAudio()"))
        assertTrue(source.contains("fun moveStarted()"))
        assertTrue(source.contains("resetMoveAudio()"))
        assertTrue(source.contains("if (!this.scene.__showdownNativeResultCues) this.scene.__showdownNativeResultCues = [];"))
        assertTrue(source.contains("this.__showdownNativeResultCues && this.__showdownNativeResultCues.length"))
        assertTrue(source.contains("var resultCue = this.__showdownNativeResultCues && this.__showdownNativeResultCues.length ? this.__showdownNativeResultCues.shift() : null;"))
        assertTrue(source.contains("this.scene.__showdownNativeResultCues.push(resultCue);"))
        assertTrue(source.contains("scheduleNativeCue(this, resultCue);"))
        assertFalse(source.contains("__showdownNativeResultCue = null"))
        assertTrue(source.contains("this.scene.__showdownNativeAudioSilent = !!kwArgs.silent;"))
        assertTrue(source.contains("seed(protocolHistoryProvider())"))
        assertTrue(source.contains("flushPendingPackets(allowSeedWhilePaused = true)"))
        assertTrue(source.contains("private val nativeIdlePauseRunnable = Runnable"))
        assertTrue(source.contains("NATIVE_IDLE_CHECK_DELAY_MILLIS"))
        assertTrue(source.contains("window.ShowdownNativeEffects.pauseWhenIdle();"))
        assertTrue(source.contains("var nativeIdlePauseTimer = null;"))
        assertTrue(source.contains("function requestNativeIdlePause()"))
        assertTrue(source.contains("if (battle.atQueueEnd)"))
        assertTrue(source.contains("pauseWhenIdle: function ()"))
        assertTrue(source.contains("clearNativeIdlePauseTimer();"))
        assertFalse(source.contains("if (resultCue && this.scene.__showdownNativeResultCue === resultCue)"))
        assertFalse(source.contains("BattlePlaybackTiming.pauseAfter(packet)"))
        assertFalse(source.contains("postDelayed(flushRunnable"))
        assertFalse(source.contains("var originalRunMoveAnim = BattleScene.prototype.runMoveAnim;"))
    }

    @Test
    fun pausedReplayAppliesItsInitialChunkBeforePausingPlayback() {
        val source = File("src/main/kotlin/dev/adrian/showdown/MainActivity.kt").readText()
        val enqueueIndex = source.indexOf("enqueueBattlePlayback(null, null, replayLines, resetOnBattleInit = false)")
        val pauseIndex = source.indexOf("if (replayStartsPaused) setReplayPaused(true)", enqueueIndex)

        assertTrue(enqueueIndex >= 0)
        assertTrue(pauseIndex > enqueueIndex)
    }
}
