package dev.adrian.showdown

data class ShowdownChangelogEntry(
    val version: String,
    val changes: List<String>
)

object ShowdownChangelog {
    fun entries(currentVersion: String) = listOf(
        ShowdownChangelogEntry(
            currentVersion,
            listOf(
                "Move health and result audio events now survive renderer handoffs, while cues only play when Showdown renders the matching animation.",
                "AYN Thor display-pose updates now preserve the upper-screen-over-lower-screen physical order after the emulator reconfigures its displays.",
                "AYN Thor's lower preview now starts after the complete upper panel and its gap, so the two screens never overlap.",
                "Lower-screen touch regions now refresh immediately when panels or battle decisions change, so fast move, switch, target, and menu taps are not dropped.",
                "Battle protocol fallbacks now surface ability, item, stat-change, and status announcements in readable Showdown-style wording.",
                "Team sets now use four separate searchable move slots, matching Showdown's editor while preserving packed and text exports.",
                "Team editors now offer Stellar as a Tera type and reject duplicate moves before saving.",
                "Team packed exports now match Showdown's current advanced field order while still reading teams saved by earlier client versions.",
                "New teams now start with a competitive format instead of Random Battle when no format has been chosen.",
                "Team sets now edit EVs and IVs in readable HP, Atk, Def, SpA, SpD, and Spe controls while preserving Showdown's packed and text formats.",
                "The upper battle messages now behave like a Pokémon battle message box: one complete compact event at a time, with a readable dwell and gentle fade between events.",
                "Battle message fades now keep the white text and dark outline readable until the event leaves the upper display.",
                "The lower command deck now keeps battle-action text on the upper display and shows only the current choice prompt below.",
                "Thor party indicators now use smooth high-definition ready, statused, and fainted Poké Ball artwork instead of enlarged pixel glyphs.",
                "Singles battle sprites now use Showdown's near-side and far-side field anchors, including the correct player-side baseline and scale.",
                "The sprite preference now clearly distinguishes HD animated sprites from the Gen 5 classic family.",
                "Battle and team-preview sprites now try runtime HD animated, credit-permitted community, and high-resolution artwork before falling back cleanly when a species or form is unavailable.",
                "Singles HP cards now share one Pokémon-style frame, keep their full names readable, and stay clear of the sprites.",
                "The switch screen now uses two wide columns with separated sprite, name, level, HP, type, and status regions.",
                "Battle history snapshots no longer replay as a burst when the live Showdown feed takes over; only new events enter the readable message queue.",
                "Replayed protocol history now stays out of the live message queue, preventing reconnects and resumed battles from rebuilding an old text backlog.",
                "Battle messages now appear one readable event at a time instead of building a wall of text, and the feed freezes cleanly when the app leaves the foreground.",
                "Effectiveness battle audio now waits for the generic damage sample to finish, keeping the hit and result cues audibly sequential.",
                "Battle message separators now let the current event finish before the next queued event appears.",
                "Modern battles now prefer high-resolution artwork before regular animated Showdown sprites when an HD animation is unavailable.",
                "Damage, effectiveness, and stat audio now starts on Showdown's matching visual event and is cancelled when animation playback pauses or resets.",
                "Compact multi-battle HP cards now keep a readable Poké Ball strip on smaller Thor display surfaces, even before party details arrive from the server.",
                "Saved Random Doubles Battle selections now survive a server format refresh instead of silently falling back to singles.",
                "Live battle decisions now become actionable immediately while the readable send-out and move playback continues, keeping the server timer in sync.",
                "The full user-facing battle history remains available for activity and replay review without crowding the live battle surface.",
                "Thor touch and controller focus now restores cleanly after the app returns from the background.",
                "Team Library now keeps repeated confirmations from stacking duplicate custom dialogs.",
                "Multi-Pokémon battles now keep the party Poké Ball strip on the remaining visible HP card while a partner faints.",
                "Account settings can now create a registered Showdown account and finish sign-in without leaving the client.",
                "Registered Showdown sessions now survive app process restarts and restore the active battle identity before rejoining.",
                "Battle sound effects now pause and resume with their active move timing when the app leaves and re-enters the foreground.",
                "Live battle animations now pause with the app and resume cleanly after returning to the foreground.",
                "Move detail panels now use matching padded metric cards for large, readable power, accuracy, category, and target values while selector cards retain PP.",
                "Move previews now fill power, accuracy, category, and gimmick power from the official dex while keeping status and always-hit values as dashes.",
                "Type icons remain on move selectors without repeating the type label in the card or detail panel.",
                "Impact audio now starts with the damage animation instead of waiting behind longer status clips, with effectiveness cues following the hit.",
                "Battle cues now preserve their original animation timestamp while audio samples finish loading, keeping late-loaded damage and effectiveness sounds in sync.",
                "Spread moves now play one effectiveness cue per move instead of stacking the same sound once per target.",
                "Stat boost and drop audio now starts at the corresponding battle event instead of waiting for an earlier cue to finish.",
                "Battle audio timing resets at each move boundary so faster playback cannot delay the next move's cue.",
                "Damage cues also follow health changes represented by set-HP packets without sounding for healing.",
                "Dynamax and Terastal choices now use the official Showdown command suffixes.",
                "Consumed items now disappear from Pokémon details and appear in the battle log.",
                "Battle requests no longer show a Terastal action when the server explicitly disables it.",
                "Doubles item and ability updates now stay on the correct active Pokémon.",
                "Battle details now resolve nickname-based protocol identifiers to the active species.",
                "Active Pokémon details now track readable temporary battle effects until Showdown ends them.",
                "Battle inspections now distinguish turn-scoped protections from move-scoped effects and clear them on the same boundaries as Showdown.",
                "Protection blocks and Roost now update active battle state and displayed types like Showdown.",
                "Ability activations now reveal the correct ability in the active Pokémon details.",
                "Internal ability boost tokens no longer appear as unreadable battle-feed text.",
                "Duplicate species with different nicknames now keep separate party details.",
                "Duplicate opponent species now keep item, status, and form updates on the correct party member.",
                "Long multi-part form identifiers such as Alcremie-Caramel-Swirl now use the base species in readable battle labels while retaining the full form for sprites and battle state.",
                "Battle challenges announced by Showdown now open the custom accept or reject flow.",
                "Battle playback, audio cues, and the two-screen presentation remain tuned for human-speed reading.",
                "Replay links shared from another app now open directly in the native replay player, including links embedded in shared text.",
                "Active live battles now retain their room and pending choice while Android recreates the activity.",
                "The first live battle state is no longer fed into the animation layer twice, preventing duplicated opening effects and audio timing drift.",
                "Live battle choices now remain queued until Showdown acknowledges them, including across reconnects and activity recreation.",
                "Doubles and triples target selection now follows Showdown's adjacent, ally, foe, and area-target rules.",
                "Matched battles are recovered after reconnecting, even when the room ID stays the same.",
                "Battle form-change packets now keep the visible HP and status cards in sync.",
                "New battles now open on the Fight panel even when the lobby was left on Menu.",
                "Mega and Primal battle packets now keep their revealed stone or orb visible in Pokémon details.",
                "Fresh installs now default to the current Gen 9 Random Battle format.",
                "Team JSON import and export now preserve Showdown's advanced set fields.",
                "Team imports now also accept the beta client's bracketed ability and inline nature format.",
                "Shared PokePaste, Gist, and Showdown team exports now open directly in the team library, including psim.us team links.",
                "Remote team imports now keep every Pokémon from the selected Showdown export.",
                "Imported team backups now return to a refreshed team library so new teams appear immediately.",
                "Team library navigation now filters saved teams by Showdown format as well as folder and search.",
                "Team format pickers now show readable Showdown names without exposing raw IDs in the selection list.",
                "Challenge dialogs now use the readable advertised Showdown format name instead of a raw format ID.",
                "Team selection and tournament surfaces now use readable Showdown format names throughout.",
                "Custom dialogs no longer open the keyboard automatically, keeping their actions visible until an input is tapped.",
                "Iron Valiant now uses verified rear-facing artwork on the player side and never falls back to its front sprite.",
                "Active battle sprites now resolve from species identifiers while keeping nicknames readable in the battle UI.",
                "Singles battles now use the same species-resolved active sprite path as multi-Pokémon battles.",
                "Concurrent sprite, effect, audio, and data requests now share downloads without dropping waiting callbacks.",
                "Active Pokémon now use side-specific placeholders while a switched-in sprite loads, preventing stale orientation flashes.",
                "The secondary Thor display keeps controller focus available for touch and hardware input.",
                "Lower-screen controls now size themselves from the Thor lower panel's actual display density instead of inheriting the upper-screen metrics.",
                "Unknown move records no longer arm the generic damage cue, preventing sound effects from being attached to unclassified animations.",
                "Residual damage from status effects, items, and hazards no longer produces a false direct-hit haptic.",
                "Direct HP changes now trigger one impact feedback only when the target actually loses HP, including set-HP damage packets.",
                "Native battle effects now use Showdown's set-HP delta when deciding whether to play direct damage audio, keeping healing silent.",
                "Multi-target set-HP packets now update every active Pokémon and keep each impact feedback event attached to the right target.",
                "Active form updates and custom end-of-Terastal packets now restore Pokémon details and original types correctly.",
                "Battle sprite requests now carry their battle side explicitly, keeping player-side Iron Valiant artwork rear-facing in every battle layout.",
                "Compact doubles and triples HP cards now use the same species-resolved identity and live HP projection as the cleaned single-battle layout, without party or battle metadata clutter.",
                "Triple-battle target choices now flow onto a second readable row so every legal target remains touchable.",
                "Damage audio now resets at every official move event, including moves marked [still], so skipped animations cannot leak timing into the next move.",
                "Direct-hit audio now follows the current damaging move only, leaving misses, residual effects, recoil, hazards, and healing silent.",
                "Damage audio now ignores non-damaging Physical and Special moves unless Showdown reports real damage power or a custom damage handler.",
                "Battle animations now stay at the selected playback speed instead of Showdown's automatic late-battle acceleration making later turns unexpectedly faster.",
                "Random doubles, triples, and Battle Factory matchmaking now start without incorrectly asking for a saved team.",
                "The Thor secondary display now reapplies touch and controller focus when its presentation is recreated or regains window focus.",
                "Starting another battle now clears stale lobby, team, account, and room overlays so old dialogs cannot cover the new battle.",
                "Singles, doubles, and triples now share one compact HP-card content treatment with only the card density changing.",
                "Matchmaking now honors Showdown's advertised format capabilities and falls back from challenge-only saved formats before searching.",
                "Illusion reveals now replace the temporary battle identity without carrying stale Pokémon details into the active battle state.",
                "Ultra Burst form changes now retain nicknames and reveal the correct burst item in Pokémon details.",
                "Transform now keeps the transformed Pokémon's nickname while copying the target's actual species and revealed battle details.",
                "Form changes now retain the active level and gender when Showdown sends a species-only details packet.",
                "Visible nicknames now stay separate from species across requests, switches, HP cards, and Pokémon inspection.",
                "Sparse doubles and triples requests now keep each move list, active card, and choice attached to its real battle slot.",
                "Multi-battle foe targets now use Showdown's required +slot choice syntax.",
                "Live battle feeds now keep Showdown's move, effect, and damage messages readable without exposing parser diagnostics.",
                "The upper battle feed now combines the live protocol transcript with Showdown's native log as animations catch up, so move and effect messages cannot disappear or interrupt the readable queue.",
                "Native Showdown battle wording now replaces protocol fallbacks in place, preventing duplicate readable lines while the battle feed catches up.",
                "Effectiveness cues now stay attached when Showdown reports them after damage, while indirect damage still stays silent.",
                "Anonymous guest battles now reconnect as read-only spectators after an app process restart instead of showing a stale battle transcript.",
                "Live battle rooms and pending choices now flush to disk before the app is backgrounded or the process is killed.",
                "AYN Thor emulator sessions now keep the 1920×1080 upper panel above the 1240×1080 lower panel in the single-window preview.",
                "Fainted Pokémon now keep their zero-HP card and party Poké Balls visible while their field sprite leaves play.",
                "Switch cards now reserve separate type and status regions at the Thor lower display density, keeping long type names inside their own card.",
                "Switch cards now derive their sprite, header, HP, type, and status regions from each card's available height, preventing six-Pokémon switch screens from overlapping.",
                "Switch-card text now fits both its width and vertical region, keeping names, HP, and status labels inside their cards across display sizes.",
                "Switch-card text is now clipped to its own name, level, HP, type, and status region so no label can bleed into another control.",
                "Forced switch and team-preview states now use concise lower-screen titles so the current decision is clear without covering the card grid.",
                "Submitted switch choices now show a waiting state instead of leaving inactive cards looking selectable.",
                "Mandatory switch and team-preview decisions now render in an isolated full-screen replacement grid, keeping the prompt and cards separate from regular battle controls.",
                "Switch-screen transitions now discard the previous move interaction state before drawing the dedicated team decision surface, preventing controls from leaking into the switch page.",
                "Forced switch requests now keep the dedicated card grid visible during live-state handoffs instead of falling back to an overlapping empty-team panel.",
                "Lower-screen panel changes now clear the custom canvas state before drawing, preventing stale translucent controls from showing through the switch screen.",
                "Thor presentation replacement now waits for the previous lower-screen surface to dismiss, preventing stacked switch screens after lifecycle or display changes.",
                "Thor lower-screen presentation creation now recovers cleanly if Android removes the target display during the window handoff.",
                "The lower-screen presentation now closes when the app leaves the foreground and is rebuilt on resume, preventing stale switch controls from surviving an app restart.",
                "Thor display callbacks now wait for the activity to be resumed before creating a lower-screen presentation, closing a paused-state race during display handoffs.",
                "Switch cards now derive disjoint sprite, name, level, HP, type, and status regions at the Thor lower display size, with the active Pokémon marked unavailable instead of presented as another switch choice.",
                "Forced switch cards now keep selected replacements visibly marked and show multi-switch progress.",
                "Switch-screen controller focus now follows the same two-column grid that is rendered on the Thor display.",
                "Native battle messages now follow the local player side, so move wording matches the upper HP cards in every matchup.",
                "Recovered guest battles now clearly show WATCHING and the latest battle event on the lower display instead of a stale waiting message.",
                "Dynamic Showdown battle announcements now replace their previous text instead of leaving stale duplicate lines in the feed.",
                "Battle failure messages now stay readable when Showdown omits the optional effect name."
            )
        ),
        ShowdownChangelogEntry(
            "v0.1.0-alpha.3",
            listOf(
                "Added an in-app What's new changelog to the Info & resources screen.",
                "Release APK assets now use the lowercase showdown- filename prefix.",
                "Improved challenge notifications and private-message handling."
            )
        ),
        ShowdownChangelogEntry(
            "v0.1.0-alpha.2",
            listOf(
                "Added a signed installable alpha release for Android.",
                "Added adjustable replay speed.",
                "Refined the custom Thor UI, battle log contrast, and readable battle information."
            )
        ),
        ShowdownChangelogEntry(
            "v0.1.0-alpha.1",
            listOf(
                "Added live Showdown battles, team building, replays, rooms, chat, and account tools.",
                "Added dual-screen battle presentation with touch and controller support."
            )
        )
    )
}
